apiVersion: v1
kind: Pod
metadata:
  name: secret-example-pod
spec:
  containers:
    - name: secret-test-container
      image: busybox
      command: [ "/bin/sh", "-c", "sleep 30m" ]
      volumeMounts:
        # name must match the volume name below
        - name: secret-volume
          mountPath: /sec
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: restmock-secret
  restartPolicy: Never